BEGIN TRAN A;
-- PATCH TO FORCE USE LAST ADDED CAR IN CASE THE FK SCRIPT BREAKS. THIS SHOULD NOT BE EXECUTED. IT IS CAUSED BY EXISTING TRACKER ENTRIES WITH NULL CAR_ID
-- BEGIN
--DECLARE @DefaultCarID INT=(SELECT [Id] FROM [CarFleet] WHERE [Id]=(SELECT MAX(Id) FROM [CarFleet]))
--UPDATE [Tracker] SET [Car_Id]=@DefaultCarID WHERE [Car_Id] IS NULL
-- END

ALTER TABLE [Tracker] ALTER COLUMN [Car_Id] INT NOT NULL

ALTER TABLE [Tracker] 
	ADD CONSTRAINT 
	FK_Tracker_CarFleet FOREIGN KEY  (Car_Id) REFERENCES CarFleet(Id)

COMMIT;